#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

APP_PY_VERSION="3.10.13"
echo ">> create conda env '${SD_WEBUI_APP_NAME}'"
conda create -y --name "${SD_WEBUI_APP_NAME}" python=${APP_PY_VERSION}
