#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

echo ">> install assist client service"

systemctl daemon-reload
systemctl enable install-assist-client.service
