#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

check_kernel() {
    # comparing chroot kernel with host kernel
    CHROOT_KERNEL=$(dpkg -l | awk '/^.i +linux-(im)/&& $2~/[0-9]/{print substr($2,13)}')
    HOST_KERNEL=$(uname -r)
    echo "CHROOT_KERNEL: $CHROOT_KERNEL, HOST_KERNEL: $HOST_KERNEL"
    if [ "$CHROOT_KERNEL" != "$HOST_KERNEL" ]; then
        echo "ERROR: kernel mismatch! CHROOT_KERNEL:$CHROOT_KERNEL HOST_KERNEL:$HOST_KERNEL"
        exit 1
    fi
}

install_kernel() {
    sudo apt-get -y install build-essential linux-image-$(uname -r) linux-headers-$(uname -r) dkms
}

freeze_kernel() {
    # prevent kernel from being upgraded
    sudo apt-mark hold linux-image-generic linux-headers-generic
}

check_kernel
install_kernel
freeze_kernel