#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

find_best_package_version() {
    # $1: package name, $2: expected version (e.g. 560.35.05)
    local pkg_name="$1"
    local expected_version="$2"
    apt-cache madison "$pkg_name" | grep "$expected_version" | awk '{print $3}' | head -n1
}

install_nvidia_driver() {
    major_version=${NVIDIA_DRIVER_VERSION%%.*}
    sudo apt-get -y install --no-install-recommends \
        nvidia-driver-${major_version}=$(find_best_package_version "nvidia-driver-${major_version}" "$NVIDIA_DRIVER_VERSION") \
        nvidia-modprobe=$(find_best_package_version "nvidia-modprobe" "$NVIDIA_DRIVER_VERSION")

    # don't enable nvidia-persistenced.service on default
    sudo systemctl disable nvidia-persistenced
}

freeze_nvidia_driver() {
    major_version=${NVIDIA_DRIVER_VERSION%%.*}
    # prevent nvidia driver from being upgraded
    sudo apt-mark hold nvidia-driver-${major_version}
}

install_nvidia_driver
freeze_nvidia_driver
echo "Nvidia Driver ${NVIDIA_DRIVER_VERSION} installed"
