#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

version_short() {
    echo $1 | awk -F'.' '{print $1 "." $2}'
}

find_best_package_version() {
    # $1: package name, $2: expected version (e.g. 560.35.05)
    local pkg_name="$1"
    local expected_version="$2"
    apt-cache madison "$pkg_name" | grep "$expected_version" | awk '{print $3}' | head -n1
}

install_cuda_driver() {
    major_version=${CUDA_DRIVER_VERSION%%.*}
    sudo apt-get -y install \
        cuda-drivers-${major_version}=$(find_best_package_version "cuda-drivers-${major_version}" "$CUDA_DRIVER_VERSION") \
        nvidia-driver-${major_version}=$(find_best_package_version "nvidia-driver-${major_version}" "$CUDA_DRIVER_VERSION")
}

freeze_cuda_driver() {
    major_version=${CUDA_DRIVER_VERSION%%.*}
    # prevent nvidia driver from being upgraded
    sudo apt-mark hold cuda-drivers-${major_version}
    sudo apt-mark hold nvidia-driver-${major_version}
}

install_nvidia_dkms() {
    major_version=${CUDA_DRIVER_VERSION%%.*}
    sudo apt-get -y install nvidia-dkms-${major_version}=$(find_best_package_version "cuda-drivers-${major_version}" "$CUDA_DRIVER_VERSION")
    sudo apt-mark hold nvidia-dkms-${major_version}
}

# https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#common-installation-instructions-for-ubuntu
install_cuda_toolkit() {
    cuda_version=$(version_short $CUDA_VERSION)
    cuda_version=${cuda_version//./-}
    sudo apt-get -y install \
        cuda-toolkit-${cuda_version}=$(find_best_package_version "cuda-toolkit-${cuda_version}" "$CUDA_VERSION")
    sudo apt-get -y install \
        nvidia-gds-${cuda_version}=$(find_best_package_version "nvidia-gds-${cuda_version}" "$CUDA_VERSION")
}

install_cudnn() {
    major_cudnn_version=${CUDNN_VERSION%%.*}
    if [[ $major_cudnn_version -eq 8 ]]; then
        cuda_version=$(version_short $CUDA_VERSION)
        sudo apt-get -y install \
            libcudnn8=$CUDNN_VERSION-1+cuda${cuda_version} \
            libcudnn8-dev=$CUDNN_VERSION-1+cuda${cuda_version}
    elif [[ $major_cudnn_version -eq 9 ]]; then
        major_cuda_version=${CUDA_VERSION%%.*}
        sudo apt-get -y install \
            libcudnn9-cuda-${major_cuda_version}=$(find_best_package_version "libcudnn9-cuda-${major_cuda_version}" "$CUDNN_VERSION") \
            libcudnn9-dev-cuda-${major_cuda_version}=$(find_best_package_version "libcudnn9-dev-cuda-${major_cuda_version}" "$CUDNN_VERSION")
    fi
}

add_path() {
    echo 'PATH="$PATH:/usr/local/cuda/bin"' >/etc/profile.d/099_cuda.sh
    chmod +x /etc/profile.d/099_cuda.sh
}

# all in one
install_all() {
    # install_cuda_driver
    # freeze_cuda_driver
    install_nvidia_dkms
    echo "CUDA driver ${CUDA_DRIVER_VERSION} installed"
    install_cuda_toolkit
    echo "CUDA toolkit ${CUDA_VERSION} installed"
    install_cudnn
    echo "cuDNN ${CUDNN_VERSION} installed"
    add_path
    echo "add cuda bin to PATH"
}

install_all
